setwd("/Users/jingyiyuan/Desktop/Data Mining/R")
Auto = read.csv("Auto.csv", na.string = "?", header = T)
Auto <- na.omit(Auto)

attach(Auto)
range(mpg)
range(cylinders)
range(displacement)
range(horsepower)
range(weight)
range(acceleration)

mean(mpg)
sd(mpg)
mean(cylinders)
sd(cylinders)
mean(displacement)
sd(displacement)
mean(horsepower)
sd(horsepower)
mean(weight)
sd(weight)
mean(acceleration)
sd(acceleration)

Auto_01 = Auto[10:85,]
Auto_01 = na.omit(Auto_01)
range(mpg)
mean(mpg)
sd(mpg)
range(cylinders)
mean(cylinders)
sd(cylinders)
range(displacement)
mean(displacement)
sd(displacement)
range(horsepower)
mean(horsepower)
sd(horsepower)
range(weight)
mean(weight)
sd(weight)
range(acceleration)
mean(acceleration)
sd(acceleration)

pairs(Auto)

